1. Adding a subtracting matrices

In [11]:
import numpy as np

A = np.matrix([[1,2],[3,4]])
B = np.matrix([[7,6],[9,8]])

print("A=\n", A)
print("B=\n", B)

print("A+B=\n", np.add(A, B))
print("A-B=\n", np.subtract(A, B))

A=
 [[1 2]
 [3 4]]
B=
 [[7 6]
 [9 8]]
A+B=
 [[ 8  8]
 [12 12]]
A-B=
 [[-6 -4]
 [-6 -4]]


2. Multiply 2 matrices

In [12]:
import numpy as np

A = [[1,2],
     [2,3],
     [3,1]]

B = [[1,2,3,4],
     [3,2,1,4]]

print("A.B\n", np.dot(A, B))

A.B
 [[ 7  6  5 12]
 [11 10  9 20]
 [ 6  8 10 16]]


3. Tranpose of a matrix

In [25]:
A = np.matrix([[1,2,3],
               [2,3,4]])

print("Transpose of A is \n", A.T)

B = [(1,2,3),
     (2,3,4)]

BT = map(list, zip(*B))
print("Transpose of B is")
for row in BT:
    print(row)

Transpose of A is 
 [[1 2]
 [2 3]
 [3 4]]
Transpose of B is
[1, 2]
[2, 3]
[3, 4]


4. Vertical Concatenation of strings

In [44]:
from itertools import zip_longest as zl

list = [["Potatoes", "Beast"], ["are", "is"], ["good", "killing"],["", "him"]]

final = [" ".join(ele) for ele in zl(*list, fillvalue="")]

print(str(final))

['Potatoes are good ', 'Beast is killing him']


5. 